from typing import Protocol, Optional
from datetime import timedelta


class TokenRepository(Protocol):
    async def add_to_blacklist(self, token: str, expires_in: timedelta) -> None: ...
    async def is_blacklisted(self, token: str) -> bool: ...
    async def add_to_cache(self, token: str, user_id: str, expires_in: timedelta) -> None: ...
    async def get_cached_user_id(self, token: str) -> Optional[str]: ...
    async def remove_from_cache(self, token: str) -> None: ... 
